### ISSUE TITLE
Can't get bond to use Homebrew readline

### ISSUE THREAD

**Issue by swrobel** [cldwalker/bond#42]
```
$ brew --prefix readline
/usr/local/opt/readline

$ gem install bond -- --with-readline-dir=`brew --prefix readline`  
Fetching: bond-0.5.1.gem (100%)
Building native extensions with: '--with-readline-dir=/usr/local/opt/readline'
This could take a while...
Successfully installed bond-0.5.1
1 gem installed

$ rib      
Bond has detected EditLine and may not work with it. See the README's Limitations section.
>> 
```

Pounding my head against the wall... :finnadie:

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 12 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/bond#42). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by godfat** [comment]
Well, actually bond doesn't really need C extension for newer Ruby:
https://github.com/cldwalker/bond/blob/v0.5.1/ext/readline_line_buffer/extconf.rb#L8-L11
It's only used for older rubies which lacks some API from ruby's readline extension.

I would still suggest just `brew install ruby` and you'll be fine, otherwise I just found this,
I am not sure if this would help, but it has some instructions:
https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X

**Comment by swrobel** [comment]
Thanks @godfat. `gem install bond -- --without-readline` got rid of the EditLine warning on startup.
